apiVersion: orionmesh.dev/v1
kind: Service
metadata:
  name: watcher-python
  labels:
    role: processor
    queue: ps-broadcast
    lang: python
spec:
  runtime:
    kind: native
    exec: python
    args:
    - examples/10-queues/python/processor.py
    env:
      NATS_URL: nats://127.0.0.1:4222
      ORION_QUEUE_NAME: ps-broadcast
      ORION_QUEUE_SUBJECT: orion.queue.ps-broadcast
      ORION_QUEUE_STREAM: ORION_QUEUE_PS_BROADCAST
      ORION_QUEUE_TYPE: topic
      ORION_QUEUE_GROUP: ps-broadcast-watchers
  replicas: 2
  restart_policy: on_failure
